# Generated by Django 5.0.6 on 2024-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(help_text='Name this document', max_length=100)),
                ('doc_priority', models.IntegerField(help_text='Give this document a number between 1 and 10 to describe its priority')),
                ('doc_tag', models.CharField(help_text='Give this document a tag', max_length=100)),
                ('doc_description', models.TextField(help_text='Give this document a short description', max_length=750)),
                ('doc_last_alteration', models.DateField(help_text='Date from the last alteration made in this document')),
            ],
            options={
                'ordering': ['doc_name', '-doc_tag', '-doc_last_alteration'],
            },
        ),
    ]
