# Generated by Django 5.0.6 on 2024-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_group_name', models.CharField(help_text='Give this group of documents a name', max_length=100)),
            ],
            options={
                'ordering': ['doc_group_name'],
            },
        ),
    ]
